	<section id="discografia">
		
		<div class="centrado">

			<h1>Descargá la discografía completa de <strong>Infanto-Juvenil</strong></h1>
			
			<aside>
				<ul>
					<li>
						<a href="https://drive.google.com/open?id=0B-MCBxTP83NfVXpJMGx3cEZqRzg" target="_parent">
							<img src="img/contenido/discografia-demo-1.png" alt="Demo 1">
							<footer>
								<hgroup>
									<h1>Demo 1</h1>
									<h2>Julio 2003</h2>
									<h3>Primeros ensayos del grupo.</h3>
								</hgroup>
							</footer>
						</a>
					</li>
					<li>
						<a href="https://drive.google.com/open?id=0B-MCBxTP83NfV0czM3JYSnFjcWs" target="_parent">
							<img src="img/contenido/discografia-muestra-virginia.png" alt="Muestra para Virginia">
							<footer>
								<hgroup>
									<h1>Muestra para Virginia</h1>
									<h2>Enero 2004</h2>
								</hgroup>
							</footer>
						</a>
					</li>
					<li>
						<a href="https://drive.google.com/open?id=0B-MCBxTP83NfUS1MN3lJN3c0cHc" target="_parent">
							<img src="img/contenido/discografia-demo-2.jpg" alt="Demo 2">
							<footer>
								<hgroup>
									<h1>Demo 2</h1>
									<h2>Abril 2004</h2>
								</hgroup>
							</footer>
						</a>
					</li>
				</ul>	
			</aside>
			
			<main>
				<a href="https://infantojuvenil.bandcamp.com/album/infanto-juvenil" target="_parent">
					<img src="img/contenido/discografia-demo-3.jpg" alt="Infanto-Juvenil">
					<footer>
						<hgroup>
							<h1>Infanto-Juvenil</h1>
							<h2>Setiembre 2014</h2>
						</hgroup>
					</footer>
				</a>
			</main>

		</div>

	</section>