	<section id="historia">
		
		<div class="centrado">

			<h1>En una ciudad olvidada,<br>
			en el invierno eterno,<br>
			surge <strong>Infanto-Juvenil</strong>,<br>
			<mark>primer y único grupo <strong>punk</strong><br>
			de <strong>Piriápolis</strong>.</mark></h1>

			<a href="http://infantojuvenil.tumblr.com/tagged/historia/chrono" target="_blank">Leer la historia del grupo</a>	

		</div>
		
	</section>