	<section id="integrantes">
		
		<div class="centrado">

			<ul>
				<li>
					<img src="img/contenido/integrantes-foto-oscar.jpg" alt="Oscar">
					<h1><img src="img/contenido/integrantes-nombre-oscar.svg" alt="Oscar"></h1>
					<h2>Batería</h2>
					<p>Quería tener una banda al igual que su hermano, y comenzó reclutando gente en base a sus looks.
					Su idea de formar una banda de punk melódico se torció un poco cuando eligió a un cantante sin melodía ninguna, por lo que él mismo se encargo de componer y cantar algunas canciones.</p>
				</li>
				<li>
					<img src="img/contenido/integrantes-foto-andy.jpg" alt="Andy Pálido">
					<h1><img src="img/contenido/integrantes-nombre-andy.svg" alt="Andy Pálido"></h1>
					<h2>Voz y guitarra</h2>
					<p>Convocado al grupo por su apariencia, fue quien le puso nombre a la banda y propuso al resto de los integrantes. Su interés no estaba en la música, la veía sólo como un apoyo para transmitir letras provocativas. Tras la salida de Marcos se encargó de la guitarra y compuso nuevas canciones.</p>
				</li>
				<li>
					<img src="img/contenido/integrantes-foto-enret.jpg" alt="Enret">
					<h1><img src="img/contenido/integrantes-nombre-enret.svg" alt="Enret"></h1>
					<h2>Bajo</h2>
					<p>Fue invitado al grupo sólo por tener una cresta, al igual que Andy. 
					Comenzó tocando con el bajo desenchufado pero terminó aprendiendo. Abandonó sus estudios de secundaria y se dedicó al bajo, logrando ser premiado como mejor bajista en un concurso donde su profesor formaba parte del jurado.
					</p>
				</li>
				<li>
					<img src="img/contenido/integrantes-foto-marcos.jpg" alt="Marcos">
					<h1><img src="img/contenido/integrantes-nombre-marcos.svg" alt="Marcos"></h1>
					<h2>Guitarra</h2>
					<p>Fue el primer guitarrista del Infanto y compuso la música de las primeras canciones.
					Escribió algunas letras y por un tiempo suplantó a Andy en la voz.
					Las diferencias con Oscar y sus gustos musicales distintos lo llevaron a abandonar el grupo.
					</p>
				</li>
			</ul>

		</div>

	</section>