	<section id="letras">
		
		<div class="centrado">
		
			<ul>
				<li><a class="seleccionado">Yo no quería nacer aquí</a></li>
				<li><a>Infanto-Juvenil</a></li>
				<li><a>Mi ex-novia</a></li>
				<li><a>Nada importa</a></li>
				<li><a>Peiranos</a></li>
				<li><a>Habito natural</a></li>
				<li><a>Destino Fatal</a></li>
				<li><a>Historia pasada</a></li>
				<li><a>No quiero a nadie</a></li>
				<li><a>Camino imperfecto</a></li>
				<li><a>Gianina quiere apretar</a></li>
				<li><a>Rompiendo la pared</a></li>
				<li><a>No sabremos cumplir</a></li>
				<li><a>Juan Bautista</a></li>
				<li><a>Voto en Blanco</a></li>
			</ul>
			
			<div>

				<article>
					
					<p>Yo quería nacer en Europa u otro lado<br> 
					y me toco ser sudamericano,<br> 
					si mi alma eligió esto realmente tuvo mal gusto<br>  
					y si no lo eligió lo eligió alguien injusto<br>  
					y si yo me lo merezco diganme que hice mal,<br>  
					por qué mierda tuve que nacer en Uruguay?</p>  

					<p>Yo quería ser del primer mundo<br>  
					y sólo soy un uruguayo inmundo.<br>  
					Yo quería tener la pinta de Richard Gere<br>  
					y soy más feo que Shaquille O'Neal.<br>  
					Yo quería los músculos de Muhammad Ali<br>  
					y soy más flaco que un somalí.</p> 

					<p>Yo no quería nacer aquí,<br> 
					yo no quería ser así.<br> 
					Por qué tuve que nacer aquí?<br> 
					Por qué tuve que ser así?</p> 

					<p>Yo quería la guita de Cacho de la Cruz<br> 
					y no tengo ni para pagar la luz.<br> 
					Yo quería viajar a todos lados,<br> 
					y no he salido de Maldonado.<br> 
					Si mi alma eligió esto realmente tuvo mal gusto<br> 
					y si no lo eligió lo eligió alguien injusto<br> 
					y si yo me lo merezco diganme que hice mal,<br> 
					por qué mierda tuve que nacer en Uruguay?</p> 

					<p>Yo no quería nacer aquí,<br> 
					yo no quería ser así.<br> 
					Por qué tuve que nacer aquí?<br> 
					Por qué tuve que ser así?</p>

					<footer>Escrita por Andy</footer>

				</article>

				<article>
					
					<p>Vos me robarás<br> 
					y yo te robaré,<br> 
					vos me buscaras<br> 
					pero me escaparé.<br> 
					Me arrinconarás<br> 
					para asfixiarme de a poco,<br> 
					pero como harás<br> 
					para matar a un loco?</p> 

					<p>Yo soy tu infanto juvenil,<br> 
					Yo soy tu infanto juvenil,<br> 
					Yo soy tu infanto juvenil.</p> 

					<p>Lo tuyo es mio<br> 
					y lo mio es mio,<br> 
					te doy una pista,<br> 
					soy anarquista.<br> 
					Como no te voté<br> 
					no te obedeceré,<br> 
					libre nací y libre moriré.<br> 

					<p>Yo soy tu infanto juvenil,<br> 
					Yo soy tu infanto juvenil,<br> 
					Yo soy tu infanto juvenil.</p> 

					<p>Muchas opciones en la mesa<br> 
					menos la que me interesa,<br> 
					maldita discriminación,<br>
					la libertad no es una opción.<br> 
					Me iré al polo norte<br> 
					en busca que otro horizonte,<br> 
					al menos ahí no hay gobierno,<br> 
					no es este caos, no es este infierno.</p> 

					<p>Yo soy tu infanto juvenil,<br> 
					Yo soy tu infanto juvenil,<br> 
					Yo soy tu infanto juvenil.</p>

					<footer>Escrita por Andy</footer>

				</article>

				<article>
					
					<p>Yo estoy aquí,<br> 
					esperándote a ti,<br>
					se que no vendrás,<br>
					no sos para mi</p>

					<p>Ya son las dos<br>
					y yo te espero a vos,<br>
					adentro de mi cuarto<br>
					hay lugar para los dos.</p> 

					<p>Te llamo a cada rato<br>
					y no me atendes,¿por qué?<br>
					se que estas ahí<br>
					y no queres,lo se!</p>

					<p>Vos estas allí,<br>
					sin pensar en mi,<br>
					no entenderás<br>
					por que te quiero a ti</p>

					<p>La verdad no se<br>
					de que me enamore,<br>
					vos vendías tu cuerpo<br>
					y yo te lo compre</p>

					<p>Te llamo a cada rato<br>
					y no me atendes,¿por qué?<br>
					se que estas ahí<br>
					y no queres,lo se!</p>

					<p>Ya son las diez<br>
					y vos no apareces,<br>
					quizás estés enferma<br>
					porque es fin de mes</p>

					<footer>Escrita por Marcos</footer>

				</article>

				<article>

					<p>No me importa si me odian<br>
					o si me quieren de verdad,<br>
					no me importa el pasado,<br>
					no me importa nada más.</p>

					<p>Si la gente habla mal,<br>
					no me importa lo que digan,<br>
					porque yo soy un vejiga,<br>
					un vejiga de verdad.</p>

					<p>No,no me importa<br>
					No,no me importa<br>
					No,no me importa<br>
					No!</p>

					<p>Esta lleno de envidiosos,<br>
					pordiosero y algo más,<br>
					también gente que te quiere,<br>
					que te quiere de verdad.</p>

					<p>Pero a veces te ocultan,<br>
					toda su falsedad,<br>
					no me importa lo que digan,<br>
					lo que diga mi mamá.</p>

					<p>No,no me importa<br>
					No,no me importa<br>
					No,no me importa<br>
					No!</p>

					<footer>Escrita por Oscar</footer>

				</article>

				<article>

					<p>Tenés plata, queres más,<br> 
					ves la lata y no te aguantas,<br> 
					por segundo lo dudas,<br>
					metes la mano y escapas.</p> 

					<p>Quién pudiera ser pirata<br> 
					para robar ese tesoro,<br> 
					Quien pudiera ser Peirano<br> 
					para robar al Uruguay.</p> 

					<p>Llega el día, te descubren,<br> 
					pero no te arrepentís,<br> 
					te cogiste a 3 millones,<br> 
					así que ahora te reís.</p> 

					<p>Quién pudiera ser pirata<br> 
					para robar ese tesoro,<br> 
					Quien pudiera ser Peirano<br> 
					para robar al Uruguay.</p> 

					<p>Seguiré tu ejemplo, y el de tu hermano,<br> 
					seré glorioso, seré Peirano.<br> 
					Y quedaré en la historia para siempre,<br> 
					para siempre...</p>

					<footer>Escrita por Andy</footer>

				</article>

				<article>

					<p>No es sólo una emoción,<br>
					ni tampoco un sentimiento,<br>
					es un habito natural<br>
					que se lleva adentro.</p>

					<p>te sientes diferente<br>
					a todos los demas,<br>
					te encierras en tu ambiente<br>
					y bajas la moral.</p>

					<p>El punk te hace saltar,<br>
					no lo podrás dejar de escuchar,<br>
					el punk te hace pensar<br>
					que estas como un loco suelto.</p>

					<p>Te sientes perseguido<br>
					por la sociedad,<br>
					te miran de reojo<br>
					y sigues igual.</p>

					<p>Te vistes diferente<br>
					a todos los demás<br>
					y todos te juzgan<br>
					por tu indignidad.</p>

					<p>El punk te hace saltar,<br>
					no lo podrás dejar de escuchar,<br>
					el punk te hace pensar<br>
					que estas como un loco suelto.</p>

					<p>Estoy confundido<br>
					y un poco aturdido<br>
					de todo el chusmerio<br>
					pero tengo que enfrentar<br>
					todo lo que dicen de mi,<br>
					no dar bola a nadie más,<br>
					aunque tenga que matar,<br>
					aunque tenga que matar.</p>

					<p>El punk te hace saltar,<br>
					no lo podrás dejar de escuchar,<br>
					el punk te hace pensar<br>
					que estas como un loco suelto.</p>

					<p>Te va a matar!</p>

					<footer>Escrita por Oscar</footer>

				</article>

				<article>

					<p>Tengo miedo no me asusten por favor,<br>
					tengo una enfermedad que me puede matar,<br>
					vengan para acá,no me dejen sólo que me puedo asustar<br>
					y puedo terminar!</p> 

					<p>Cómo será la muerte?,cómo sera?<br>
					Cómo será el destino?,qué nos pasará?<br>
					Cómo será la muerte?,cómo sera?<br>
					Cómo será el destino?,qué nos pasará?<br>
					Pasará,pasará,pasará!</p> 

					<p>No se que que pasará,si mi alma se levanta,<br>
					yo me voy a asustar,me voy a cagar,<br>
					tu novia no me va a olvidar,y vos te vas a enterar,<br>
					aunque yo quiera estar,la muerte me llevará.</p> 

					<p>Cómo será la muerte?,cómo sera?<br>
					Cómo será el destino?,qué nos pasará?<br>
					Cómo será la muerte?,cómo sera?<br>
					Cómo será el destino?,qué nos pasará?<br>
					Pasará,pasará,pasará!</p>

					<footer>Escrita por Oscar</footer>

				</article>

				<article>

					<p>El pasado me persigue<br>
					y yo se lo que hice,<br>
					ahora quiero cambiar,<br>
					otra vida adoptar</p>

					<p>Sin sentido me encontré,<br>
					yo atrás no quiero volver,<br>
					tu hermana está sola<br>
					y la disfruto a cada hora.</p>

					<p>Volver para atrás<br>
					sería un final y nada más,<br>
					sólo es un sueño<br>
					lo que te podrá salvar.</p>

					<p>Volver para atrás<br>
					sería un final y nada más,<br>
					sólo es un sueño<br>
					lo que te podrá salvar.</p>

					<p>Lo de antes fue anterior,<br>
					ahora viene lo mejor,<br>
					se acabaron las pavadas,<br>
					ya no duermo con frazadas.</p>

					<p>Sin sentido me encontré,<br>
					yo atrás no quiero volver,<br>
					tu hermana está sola,<br>
					y la disfruto a cada hora.</p>

					<p>Volver para atrás<br>
					sería un final y nada más,<br>
					sólo es un sueño<br>
					lo que te podrá salvar.</p>

					<footer>Escrita por la novia del tío de Marcos (?)</footer>

				</article>

				<article>

					<p>No puedo parar de discutir,<br>
					no puedo soñar sólo en ti,<br>
					tengo que empezar a sonreír.</p>

					<p>La vida es un placer<br>
					que se tiene que vivir,<br>
					el placer es disfrutar<br>
					el mal de los demás.</p>

					<p>No tengo rencor dentro de mi<br>
					que no me deje vivir,<br>
					que no me deje vivir!</p>

					<p>No quiero a nadie<br>
					y a nadie le importo,<br>
					como odio a ésta gente,<br>
					no respetan sentimientos,<br>
					no respetan nada al fin,<br>
					sólo te quiero a ti<br>
					si vos me queres a mi<br>
					si vos me queres a mi!</p>

					<p>No puedo soñar sin despertar,<br>
					No puedo volar sin correr,<br>
					pero tengo que alcanzar<br>
					la gran meta final.</p>

					<footer>Escrita por Oscar</footer>

				</article>

				<article>

					<p>Se acabó el tiempo de pensar,<br>
					éste es el momento para actuar,<br>
					todo por un sueño que jamás cumplirás.</p> 

					<p>No es momento de parar,<br>
					no podes frenar,porque si lo haces<br>
					en éste infierno te perderás.</p> 

					<p>La luz jamás alcanzarás<br>
					y la oscuridad te tomará<br>
					y si intentas escapar<br>
					el diablo de destruirá,<br>
					la luz jamás alcanzarás.</p> 

					<p>Perdido tu estás.<br>
					aquí una vez más,<br>
					luchando por sobrevivir,<br>
					tan sólo un poco más</p> 

					<p>No te rendirás<br>
					o te morirás,<br>
					ya que en éste lugar<br>
					sólo vos estás</p> 

					<p>La luz jamás alcanzarás<br>
					y la oscuridad te tomará<br>
					y si intentas escapar<br>
					el diablo te destuirá,<br>
					la luz jamás alcanzarás.</p>

					<footer>Escrita por Enret</footer>

				</article>

				<article>

					<p>No me gustan las palabras<br> 
					que no dicen lo que siento,<br> 
					vos sabes que no te hablo,<br> 
					y por eso no te miento.</p> 

					<p>Lo difícil me aburre,<br> 
					y lo fácil no es malo, <br>
					se muy bien lo que ocurre,<br> 
					yo quiero un regalo.</p> 

					<p>Giannina quiere apretar,<br> 
					yo la voy a ayudar<br> 
					Giannina quiere apretar,<br> 
					yo la voy a ayudar.</p> 

					<p>No quiero una novia<br> 
					para regalarle una flor,<br> 
					no pienso gastar plata,<br> 
					no creo en el amor.</p> 

					<p>No estudio un discurso<br> 
					para poder apretar,<br> 
					si estoy con Giannina<br> 
					no tengo que actuar</p> 

					<p>Giannina quiere apretar,<br> 
					yo la voy a ayudar<br> 
					Giannina quiere apretar,<br> 
					yo la voy a ayudar.</p> 

					<p>Giannina,<br> 
					Giannina,<br> 
					Giannina.</p> 

					<p>Giannina quiere apretar,<br> 
					yo la voy a ayudar<br> 
					Giannina quiere apretar,<br> 
					yo la voy a ayudar</p>

					<footer>Escrita por Andy</footer>

				</article>

				<article>

					<p>Esta vida esta podrida<br>  
					y vos lo sabes muy bien,<br>  
					si no encontramos la salida,<br>  
					romperemos la pared.</p> 

					<p>Estoy harto de tus ideas,<br>  
					son iguales que las de aquel,<br>  
					vos mentis y te las ingenias para convencerme,<br>  
					pero yo no te creo.</p> 

					<p>No te creo, no te creo a vos.</p> 

					<p>Vos no sos mi futuro,<br>  
					vos no me darás nada,<br>  
					yo no elijo mi destino,<br>  
					menos es tu decisión.</p> 

					<p>Estoy harto de tus ideas,<br>  
					son iguales que las de aquel,<br>  
					vos mentis y te las ingenias para convencerme,<br>  
					pero yo no te creo.</p> 

					<p>No te creo, no te creo a vos.</p> 

					<p>No te creo, no te creo,<br>  
					te miro, y no te veo.</p> 

					<p>No te creo, no te creo a vos.</p>

					<footer>Escrita por Andy</footer>

				</article>

				<article>

					<p>Me cae muy mal<br> 
					que me llamen Oriental.<br> 
					En mi no retumba<br> 
					la Patria o la Tumba.</p> 

					<p>Si tuviera que elegir,<br> 
					seguro que un sorteo,<br> 
					me iba a ayudar,<br> 
					a decidir.</p> 

					<p>No sabremos cumplir.<br> 
					No sabremos cumplir.<br> 
					No sabremos cumplir.</p>

					<footer>Escrita por Andy</footer>

				</article>

				<article>

					<p>Juan Bautista fue el producto de una violación,<br> 
					de 10 años de miseria y mucha depresión.<br> 
					Su madre era muy jóven para tenerlo,<br> 
					pensó en abortarlo pero no pudo hacerlo.</p> 

					<p>Lo dio en adopción y lo adpotó un policía,<br> 
					que a los 2 años ya lo prostituía.<br> 
					Un día y sin saberlo estuvo con su abuela,<br> 
					teniendo relaciones en el patio de la escuela.</p> 

					<p>Una vida anormal,<br> 
					como puede tocarle a cualquiera,<br> 
					cuando todo sale mal<br> 
					y no como uno quisiera<br> 
					que fuera,<br> 
					que fuera,<br> 
					ahh!</p> 

					<p>Sufría necrofilia y era un caso serio,<br> 
					revivió a más de un muerto en el cementerio.<br> 
					Un día quiso usar el elongador peneano,<br> 
					y logró meterse su propio pene en su ano.</p> 

					<p>Tuvo sexo oral con un sadomasoquista,<br> 
					que usando sus dientes castro a Juan Bautista,<br> 
					y núnca más lo hizo en toda su vida,<br> 
					y un día se murió, apestado de sida.</p> 

					<p>Una vida anormal,<br> 
					como puede tocarle a cualquiera,<br> 
					cuando todo sale mal<br> 
					y no como uno quisiera<br> 
					que fuera,<br> 
					que fuera,<br> 
					ahh!</p> 

					<p>Juan Bautista,<br> 
					producto de una violación.<br> 
					Juan Bautista,<br> 
					producto de una violación.<br> 
					Juan Bautista,<br> 
					producto de una violación.<br> 
					Juan Bautista,<br> 
					producto de una violación.</p>

					<footer>Escrita por Andy</footer>

				</article>

				<article>

					<p>Voto en blanco.<br> 
					Todo es una mentira.<br> 
					Voto en blanco.<br> 
					Porque no hay una salida.<br> 
					Voto en blanco.<br> 
					No es momento de soñar,<br> 
					la jodita debe terminar.</p> 

					<p>Voto en blanco.<br> 
					No a las falsas promesas.<br> 
					Voto en blanco.<br> 
					No elegiré a quien me robe.<br> 
					Voto en blanco.<br> 
					Conozco el juego<br> 
					y se que núnca lo ganaré.</p> 

					<p>Voto en blanco.<br> 
					Voto en blanco.<br> 
					Voto en blanco.<br> 
					Voto en blanco.<br> 
					Voto en blanco.<br> 
					Voto en blanco yo.</p>

					<footer>Escrita por Andy</footer>

				</article>

			</div>

		</div>

	</section>